version: '3'

services:
  app:
    build: .
    container_name: deploy-gradle-app
    restart: on-failure
  nginx:
    image: nginx:mainline
    container_name: deploy-gradle-nginx
    ports:
      - "8484:80"
    volumes:
      - ./deploy-gradle.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: on-failure